wandb_version: 1

learning_rate:
  desc: null
  value: 3.90625e-06
architecture:
  desc: null
  value: CLIPPO
dataset:
  desc: null
  value: CC3M_test
epochs:
  desc: null
  value: 10000
_wandb:
  desc: null
  value:
    python_version: 3.8.17
    cli_version: 0.15.8
    framework: huggingface
    huggingface_version: 4.31.0
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1692610596.854267
    t:
      1:
      - 1
      - 5
      - 11
      - 12
      - 41
      - 49
      - 53
      - 55
      - 63
      - 75
      3:
      - 16
      - 23
      4: 3.8.17
      5: 0.15.8
      6: 4.31.0
      8:
      - 2
      - 5
