wandb_version: 1

learning_rate:
  desc: null
  value: 1.5625e-05
architecture:
  desc: null
  value: CLIPPO
dataset:
  desc: null
  value: CC3M_test
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.14.1
    framework: huggingface
    huggingface_version: 4.32.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1692602935.632664
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 63
      - 75
      3:
      - 16
      - 23
      4: 3.9.16
      5: 0.14.1
      6: 4.32.0.dev0
      8:
      - 5
