wandb_version: 1

learning_rate:
  desc: null
  value: 0.000125
architecture:
  desc: null
  value: CLIPPO
dataset:
  desc: null
  value: CC3M_test
epochs:
  desc: null
  value: 50
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.14.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1690439726.575808
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      - 63
      3:
      - 16
      - 23
      4: 3.9.16
      5: 0.14.1
      8:
      - 5
